### ISSUE TITLE
java.lang.IllegalStateException: Cannot get config value before config is loaded.   on server

### ISSUE THREAD

**Issue by moidu21** [G-Arantd/MagicCoins#4]
[24juin2025 17:43:43.691] [Server thread/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: Cannot get config value before config is loaded.

	Index: 0

	Listeners:

		0: net.neoforged.bus.EventListenerFactory$onLoad/0x00007f51ddf74000@d021e6b

java.lang.IllegalStateException: Cannot get config value before config is loaded.

	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.base.Preconditions.checkState(Preconditions.java:512)

	at TRANSFORMER/neoforge@21.1.174/net.neoforged.neoforge.common.ModConfigSpec$ConfigValue.getRaw(ModConfigSpec.java:1235)

	at TRANSFORMER/neoforge@21.1.174/net.neoforged.neoforge.common.ModConfigSpec$ConfigValue.get(ModConfigSpec.java:1222)

	at TRANSFORMER/magic_coins@1.0.6/net.sirgrantd.magic_coins.config.ServerConfig.bakeConfig(ServerConfig.java:73)

	at TRANSFORMER/magic_coins@1.0.6/net.sirgrantd.magic_coins.config.ServerConfig.onLoad(ServerConfig.java:83)

	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350)

	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315)

	at MC-BOOTSTRAP/fml_loader@4.0.39/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:158)

	at MC-BOOTSTRAP/fml_loader@4.0.39/net.neoforged.fml.config.ModConfig.setConfig(ModConfig.java:79)

	at MC-BOOTSTRAP/fml_loader@4.0.39/net.neoforged.fml.config.ConfigTracker.closeConfig(ConfigTracker.java:233)

	at java.base/java.lang.Iterable.forEach(Iterable.java:75)

	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2351)

	at MC-BOOTSTRAP/fml_loader@4.0.39/net.neoforged.fml.config.ConfigTracker.unloadConfigs(ConfigTracker.java:129)

	at TRANSFORMER/neoforge@21.1.174/net.neoforged.neoforge.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:134)

	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:750)

	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)

	at java.base/java.lang.Thread.run(Thread.java:1583)

[24juin2025 17:43:43.692] [Server thread/ERROR] [net.neoforged.fml.ModContainer/LOADING]: Caught exception during event net.neoforged.fml.event.config.ModConfigEvent$Unloading@79c0b555 dispatch for modid magic_coins

java.lang.IllegalStateException: Cannot get config value before config is loaded.

	at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.base.Preconditions.checkState(Preconditions.java:512) ~[guava-32.1.2-jre.jar%2387!/:?]

	at TRANSFORMER/neoforge@21.1.174/net.neoforged.neoforge.common.ModConfigSpec$ConfigValue.getRaw(ModConfigSpec.java:1235) ~[neoforge-21.1.174-universal.jar%23391!/:?]

	at TRANSFORMER/neoforge@21.1.174/net.neoforged.neoforge.common.ModConfigSpec$ConfigValue.get(ModConfigSpec.java:1222) ~[neoforge-21.1.174-universal.jar%23391!/:?]

	at TRANSFORMER/magic_coins@1.0.6/net.sirgrantd.magic_coins.config.ServerConfig.bakeConfig(ServerConfig.java:73) ~[magic_coins-1.0.6.jar%23565!/:?]

	at TRANSFORMER/magic_coins@1.0.6/net.sirgrantd.magic_coins.config.ServerConfig.onLoad(ServerConfig.java:83) ~[magic_coins-1.0.6.jar%23565!/:?]

	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2362!/:?]

	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%2362!/:?]

	at MC-BOOTSTRAP/fml_loader@4.0.39/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:158) ~[loader-4.0.39.jar%2359!/:4.0]

	at MC-BOOTSTRAP/fml_loader@4.0.39/net.neoforged.fml.config.ModConfig.setConfig(ModConfig.java:79) ~[loader-4.0.39.jar%2359!/:4.0]

	at MC-BOOTSTRAP/fml_loader@4.0.39/net.neoforged.fml.config.ConfigTracker.closeConfig(ConfigTracker.java:233) ~[loader-4.0.39.jar%2359!/:4.0]

	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]

	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2351) ~[?:?]

	at MC-BOOTSTRAP/fml_loader@4.0.39/net.neoforged.fml.config.ConfigTracker.unloadConfigs(ConfigTracker.java:129) ~[loader-4.0.39.jar%2359!/:4.0]

	at TRANSFORMER/neoforge@21.1.174/net.neoforged.neoforge.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:134) ~[neoforge-21.1.174-universal.jar%23391!/:?]

	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:750) ~[server-1.21.1-20240808.144430-srg.jar%23390!/:?]

	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23390!/:?]

	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

[24juin2025 17:43:43.693] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Uncaught exception in server thread

net.neoforged.fml.ModLoadingException: Loading errors encountered:

	- Magic Coins (magic_coins) encountered an error while dispatching the net.neoforged.fml.event.config.ModConfigEvent$Unloading event

	  java.lang.IllegalStateException: Cannot get config value before config is loaded.

	at MC-BOOTSTRAP/fml_loader@4.0.39/net.neoforged.fml.ModContainer.acceptEvent(ModContainer.java:162) ~[loader-4.0.39.jar%2359!/:4.0]

	at MC-BOOTSTRAP/fml_loader@4.0.39/net.neoforged.fml.config.ModConfig.setConfig(ModConfig.java:79) ~[loader-4.0.39.jar%2359!/:4.0]

	at MC-BOOTSTRAP/fml_loader@4.0.39/net.neoforged.fml.config.ConfigTracker.closeConfig(ConfigTracker.java:233) ~[loader-4.0.39.jar%2359!/:4.0]

	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]

	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2351) ~[?:?]

	at MC-BOOTSTRAP/fml_loader@4.0.39/net.neoforged.fml.config.ConfigTracker.unloadConfigs(ConfigTracker.java:129) ~[loader-4.0.39.jar%2359!/:4.0]

	at TRANSFORMER/neoforge@21.1.174/net.neoforged.neoforge.server.ServerLifecycleHooks.handleServerStopped(ServerLifecycleHooks.java:134) ~[neoforge-21.1.174-universal.jar%23391!/:?]

	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:750) ~[server-1.21.1-20240808.144430-srg.jar%23390!/:?]

	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23390!/:?]

	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by G-Arantd** [comment]
The issue has been fixed and will be updated in the next release.

**Comment by notlookme** [comment]
> The issue has been fixed and will be updated in the next release.

Hi, which release is (going to be) that? I've been getting the same (or very similar) error when stopping the server.
I'm using the modpack Create Chronicles The Endventure (with a few mods added for friends).

**Comment by E3FxGaming** [comment]
@G-Arantd Could you look into the "FTB Skies 2" modpack, installed through the official FTB server installer without any additional mods? It comes with MagicCoins version 1.0.7 and the 

```txt
[18:39:04] [Server thread/ERROR] [minecraft/MinecraftServer]: Uncaught exception in server thread
net.neoforged.fml.ModLoadingException: Loading errors encountered:
        - Magic Coins (magic_coins) encountered an error while dispatching the net.neoforged.fml.event.config.ModConfigEvent$Unloading event
          java.lang.IllegalStateException: Cannot get config value before config is loaded.
```

still occurs while shutting the server down.

Here is the server log section of the entire shutdown process, including the stacktrace of the exception.

[magic_coins_shutdown_crash.txt](https://github.com/user-attachments/files/21392004/magic_coins_shutdown_crash.txt)

Also please consider re-opening the issue.

**Comment by G-Arantd** [comment]
> [@G-Arantd](https://github.com/G-Arantd) Could you look into the ["FTB Skies 2" modpack (version 1.5.0, latest version as of writing this)](https://www.feed-the-beast.com/modpacks/129-ftb-skies-2?tab=versions), installed through the official FTB server installer without any additional mods? It comes with MagicCoins version 1.0.7 and the
> 
> [18:39:04] [Server thread/ERROR] [minecraft/MinecraftServer]: Uncaught exception in server thread
> net.neoforged.fml.ModLoadingException: Loading errors encountered:
>         - Magic Coins (magic_coins) encountered an error while dispatching the net.neoforged.fml.event.config.ModConfigEvent$Unloading event
>           java.lang.IllegalStateException: Cannot get config value before config is loaded.
> still occurs while shutting the server down.
> 
> Here is the server log section of the entire shutdown process, including the stacktrace of the exception.
> 
> [magic_coins_shutdown_crash.txt](https://github.com/user-attachments/files/21392004/magic_coins_shutdown_crash.txt)
> 
> Also please consider re-opening the issue.

Thank you for reporting this issue.

The cause of the crash has already been identified and will be fixed in the next update of the mod. However, I’m currently quite busy, so I can't give an exact date for the release. I apologize for the delay and appreciate your patience.

**Comment by G-Arantd** [comment]
> [@G-Arantd](https://github.com/G-Arantd) Could you look into the ["FTB Skies 2" modpack (version 1.5.0, latest version as of writing this)](https://www.feed-the-beast.com/modpacks/129-ftb-skies-2?tab=versions), installed through the official FTB server installer without any additional mods? It comes with MagicCoins version 1.0.7 and the
> 
> [18:39:04] [Server thread/ERROR] [minecraft/MinecraftServer]: Uncaught exception in server thread
> net.neoforged.fml.ModLoadingException: Loading errors encountered:
>         - Magic Coins (magic_coins) encountered an error while dispatching the net.neoforged.fml.event.config.ModConfigEvent$Unloading event
>           java.lang.IllegalStateException: Cannot get config value before config is loaded.
> still occurs while shutting the server down.
> 
> Here is the server log section of the entire shutdown process, including the stacktrace of the exception.
> 
> [magic_coins_shutdown_crash.txt](https://github.com/user-attachments/files/21392004/magic_coins_shutdown_crash.txt)
> 
> Also please consider re-opening the issue.

1.0.8 is ON
